baseURL = 'https://github.com/1infinitystone/xyz.git'

languageCode = 'en-us'

title = 'My New Hugo Site'

theme = "simple-dark"

defaultContentLanguage = "en"

[params]
  author = "Nakata wesley"
  description = "Your site description"
  keywords = "blog, personal"

# Optional: Configure how many posts show on homepage
paginate = 10